export const API_BASE_URL = (
  process.env.NEXT_PUBLIC_API_BASE_URL ||
  process.env.NEXT_PUBLIC_APIBASEPATH ||
  "https://localhost:44370/api"
).replace(/\/+$/, "");

export const apiUrls = {
  login: `${API_BASE_URL}/Auth/AuthenticateUser`,
  AdminLoginByOTP: `${API_BASE_URL}/Auth/AuthenticateUserByOTP`,
  CheckOTP: `${API_BASE_URL}/Auth/CheckOTP`,
  UpdatePassword: `${API_BASE_URL}/Auth/ForgotPassword`,
  ChangePassword: `${API_BASE_URL}/Auth/ChangePassword`,
  UpdateIsFirstLoginApi: `${API_BASE_URL}/Auth/UpdateLoginStatus`,
  RefreshToken: `${API_BASE_URL}/Token/GenerateToken`,

  // Policy Master (Clients -> Step 4)
  InsertPolicyMaster: `${API_BASE_URL}/PolicyMaster/InsertPolicyMaster`,
  PolicyMaster: `${API_BASE_URL}/PolicyMaster/GetPolicyMasterList`,
  PolicyMasterUpdate: `${API_BASE_URL}/PolicyMaster/UpdatePolicyMaster`,
  PolicyMasterDelete: `${API_BASE_URL}/PolicyMaster/DeletePolicyMaster`,
  GetPolicyMasterList: `${API_BASE_URL}/PolicyMaster/GetPlolicyMasterById`,
  GetPolicyMasterId: `${API_BASE_URL}/PolicyMaster/GetPolicyMasterById`,
  GetDropdownProduct: `${API_BASE_URL}/ProductMaster/GetDropdownProduct`,
  InsurerMaster: `${API_BASE_URL}/InsurerMaster/GetDropdownInsurerMaster`,
  TPAMaster: `${API_BASE_URL}/TPAMaster/GetDropdownTPAMaster`,
  GetDropdownInsurerMaster: `${API_BASE_URL}/InsurerMaster/GetDropdownInsurerMaster`,
  GetDropdownTPA: `${API_BASE_URL}/TPAMaster/GetDropdownTPAMaster`,
  GetDropdownCorporatePolicy: `${API_BASE_URL}/Employer/GetDropdownCorporatePolicy`,
  faqMaster: {
    list: `${API_BASE_URL}/FaqMaster/GetAllFaqData`,
    getById: `${API_BASE_URL}/FaqMaster/GetFaqByID`,
    create: `${API_BASE_URL}/FaqMaster/InsertFaqData`,
    update: `${API_BASE_URL}/FaqMaster/UpdateFaqData`,
    remove: `${API_BASE_URL}/FaqMaster/DeleteFaqDataID`,
    export: `${API_BASE_URL}/FaqMaster/Get_FAQ_Master_Export`,
  },
  cdBalance: {
    getBalance: `${API_BASE_URL}/CDBalance/GetCDBalance`,
    getLedger: `${API_BASE_URL}/CDBalance/GetCDBalanceList`,
    getByCorporate: `${API_BASE_URL}/CDBalance/GetCDBalanceByCorporate`,
    insertAndUpdate: `${API_BASE_URL}/CDBalance/InsertAndUpdateCDBalance`,
    getTopUpRequestForCRM: `${API_BASE_URL}/CDBalance/GetTopUpRequestForCRM`,
    handleTopUpRequest: `${API_BASE_URL}/CDBalance/HandleTopUpRequest`,
    paymentMethods: `${API_BASE_URL}/GenericMaster/GetDropdownPaymentMethod`,
    transactionTypes: `${API_BASE_URL}/GenericMaster/GetDropdownTransactionType`,
  },
  Get_Policy_Master_Export: `${API_BASE_URL}/PolicyMaster/Get_Policy_Master_Export`,

  communication: {
    eventList: `${API_BASE_URL}/MailEventMaster/GetMailEventMasterList`,
    eventDropdown: `${API_BASE_URL}/EmailTemplate/GetEmailEventDropdown`,
    eventCreate: `${API_BASE_URL}/MailEventMaster/InsertMailEventMaster`,
    eventUpdate: `${API_BASE_URL}/MailEventMaster/UpdateMailEventMaster`,
    eventDelete: `${API_BASE_URL}/MailEventMaster/DeleteMailEventMaster`,
    subEventList: `${API_BASE_URL}/EmailSubEvent/GetAllSubEventData`,
    subEventDropdown: `${API_BASE_URL}/EmailTemplate/GetEmailSubEventDropdown`,
    subEventCreate: `${API_BASE_URL}/EmailSubEvent/InsertSubEventData`,
    subEventUpdate: `${API_BASE_URL}/EmailSubEvent/UpdateSubEventData`,
    subEventDelete: `${API_BASE_URL}/EmailSubEvent/DeleteSubEventDataID`,
    corporateList: `${API_BASE_URL}/Employer/GetDropdownCorporate`,
    templateList: `${API_BASE_URL}/EmailTemplate/GetEmailContentTable`,
    templateDropdown: `${API_BASE_URL}/EmailTemplate/GetEmailTemplateNmaeDropdown`,
    filterDropdown: `${API_BASE_URL}/EmailTemplate/GetEmailFIlterDropdown`,
    templateCreate: `${API_BASE_URL}/EmailTemplate/InsertEmailContnet`,
    templateUpload: `${API_BASE_URL}/EmailTemplate/BulkUploadFiles`,
    templateById: `${API_BASE_URL}/EmailTemplate/GetEmailContentTableById`,
    templateUpdate: `${API_BASE_URL}/EmailTemplate/UpdateEmailContentTableById`,
    templateDelete: `${API_BASE_URL}/EmailTemplate/DeleteEmailContentTable`,
    submitReview: `${API_BASE_URL}/EmailTemplate/InsertEmailContnetReview`,
    reviewList: `${API_BASE_URL}/EmailTemplate/GetEmailTempalteData`,
    reviewUpdate: `${API_BASE_URL}/EmailTemplate/Update_EmailTempalteData`,
    reviewById: `${API_BASE_URL}/EmailTemplate/GetEmailTemplateReivewById`,
    employeeAllocation: `${API_BASE_URL}/EmailTemplate/GetEmployeeMailAllocationTable`,
    employeeAllocationStartStop: `${API_BASE_URL}/EmailTemplate/GetEmployeeMailAllocationTableForSartStop`,
    allocationSave: `${API_BASE_URL}/EmailTemplate/InsetEmailMailAllocation`,
    allocationStartStop: `${API_BASE_URL}/EmailTemplate/UpdateEmailMailAllocationToStopStart`,
    bulkSend: `${API_BASE_URL}/EmailTemplate/BulkUploadFiles`,
    deliveryReport: `${API_BASE_URL}/EmailTemplate/GetEmailReportTableData`,
    templateReport: `${API_BASE_URL}/EmailTemplate/IBS_EmailTemplateReportDataTable`,
    sampleUpload: `${API_BASE_URL}/EmailTemplate/UploadFile`,
    sampleList: `${API_BASE_URL}/EmailTemplate/GetEmailTemplateTable`,
    sampleDelete: `${API_BASE_URL}/EmailTemplate/DeleteSampleEmail`,
    samplePath: `${API_BASE_URL}/EmailTemplate/GetPathFromBackend`,
    fileDownload: `${API_BASE_URL}/EmailTemplate/DownloadFile`,
    channelSend: `${API_BASE_URL}/CommunicationChannel/SendOrSchedule`,
    channelJobs: `${API_BASE_URL}/CommunicationChannel/GetJobs`,
  },
  operations: {
    corporateDropdown: `${API_BASE_URL}/Employer/GetDropdownCorporate`,
    corporatePolicyDropdown: `${API_BASE_URL}/Employer/GetDropdownCorporatePolicy`,
    createBatch: `${API_BASE_URL}/Endorsement/CreateBatch`,
    batchList: `${API_BASE_URL}/Endorsement/GetBatchList`,
    createOperation: `${API_BASE_URL}/Endorsement/CreateOperation`,
    operationList: `${API_BASE_URL}/Endorsement/GetOperationList`,
    operationById: `${API_BASE_URL}/Endorsement/GetOperationByID`,
    uploadRecords: `${API_BASE_URL}/Endorsement/UploadRecords`,
    validateRecords: `${API_BASE_URL}/Endorsement/ValidateRecords`,
    operationPreview: `${API_BASE_URL}/Endorsement/GetOperationPreview`,
    processedOperationMembers: `${API_BASE_URL}/Endorsement/GetProcessedOperationMembers`,
    communicationEmployees: `${API_BASE_URL}/Endorsement/GetCommunicationEmployees`,
    updateRecordField: `${API_BASE_URL}/Endorsement/UpdateRecordField`,
    removeRecord: `${API_BASE_URL}/Endorsement/RemoveRecord`,
    resolveSpecialCase: `${API_BASE_URL}/Endorsement/ResolveSpecialCase`,
    submitOperation: `${API_BASE_URL}/Endorsement/SubmitOperation`,
    recordReviewAction: `${API_BASE_URL}/Endorsement/RecordReviewAction`,
    approveOperation: `${API_BASE_URL}/Endorsement/ApproveOperation`,
    revertRecord: `${API_BASE_URL}/Endorsement/RevertRecord`,
    revertOperation: `${API_BASE_URL}/Endorsement/RevertOperation`,
    generateTpaFile: `${API_BASE_URL}/Endorsement/GenerateTPAFile`,
    sendTpaMail: `${API_BASE_URL}/Endorsement/SendTPAMail`,
    sendTpaBatchMail: `${API_BASE_URL}/Endorsement/SendTPABatchMail`,
    processIntoSystem: `${API_BASE_URL}/Endorsement/ProcessIntoSystem`,
    uploadUserData: `${API_BASE_URL}/UploadUserMaster/UploadUserData`,
    CreateEnrollmentInceptionBatch: `${API_BASE_URL}/EmployeeEnrollment/CreateEnrollmentInceptionBatch`,
    uploadedUsers: `${API_BASE_URL}/UploadUserMaster/GetUploadedUser`,
    tasks: `${API_BASE_URL}/Endorsement/GetMyTasks`,
    auditTrail: `${API_BASE_URL}/Endorsement/GetAuditTrail`,
    uploadEcardChunk: `${API_BASE_URL}/TPAEcard/UploadEcardChunk`,
    finalizeEcardUpload: `${API_BASE_URL}/TPAEcard/FinalizeEcardUpload`,
    pendingEcardUploads: `${API_BASE_URL}/TPAEcard/GetPendingEcardUploads`,
  },
  accessManagement: {
    users: `${API_BASE_URL}/Employer/GetAllIbsUserMasters`,
    userDropdown: `${API_BASE_URL}/UserMaster/GetDropdownUserMaster`,
    roles: `${API_BASE_URL}/RoleMaster/GetRoleDropdown`,
    menus: `${API_BASE_URL}/MenuMaster/GetDropdownMenu`,
    userRoleList: `${API_BASE_URL}/UserRoleMaster/GetUserRoleMasterList`,
    userRoleSave: `${API_BASE_URL}/UserRoleMaster/InsertUserRoleMaster`,
    userRoleUpdate: `${API_BASE_URL}/UserRoleMaster/UpdateUserRoleMaster`,
    roleRightsGet: `${API_BASE_URL}/RoleMenuMappingMaster/GetRoleMenuMappingByUserId`,
    roleRightsSave: `${API_BASE_URL}/RoleMenuMappingMaster/InsertAndUpdateRoleMenuMaster`,
    userRightsGet: `${API_BASE_URL}/UserRoleMenuMaster/GetUserRoleMenuByUserId`,
    userRightsSave: `${API_BASE_URL}/UserRoleMenuMaster/InsertAndUpdateUserRoleMenuMaster`,
    corporates: `${API_BASE_URL}/Employer/GetDropdownCorporate`,
    crmAccessList: `${API_BASE_URL}/AccessManagement/GetCrmAccessList`,
    crmAccessSave: `${API_BASE_URL}/AccessManagement/SaveCrmAccess`,
    userSave: `${API_BASE_URL}/AccessManagement/SavePortalUser`,
    userStatus: `${API_BASE_URL}/AccessManagement/SetPortalUserStatus`,
    userPasswordReset: `${API_BASE_URL}/AccessManagement/ResetPortalUserPassword`,
    userRoleAssign: `${API_BASE_URL}/AccessManagement/AssignPortalUserRole`,
    userRoleRemove: `${API_BASE_URL}/AccessManagement/RemovePortalUserRole`,
  },
  menuMaster: {
    upsert: `${API_BASE_URL}/MenuMaster/UpsertMenuMaster`,
    list: `${API_BASE_URL}/MenuMaster/GetMenuList`,
    getById: `${API_BASE_URL}/MenuMaster/GetMenuById`,
    remove: `${API_BASE_URL}/MenuMaster/DeleteMenu`,
    parentDropdown: `${API_BASE_URL}/MenuMaster/GetMenuParentDropDown`,
    portalDropdown: `${API_BASE_URL}/MenuMaster/GetPortalDropdown`,
  },
  menuActionMaster: {
    upsert: `${API_BASE_URL}/ActionMaster/UpsertActionMaster`,
    list: `${API_BASE_URL}/ActionMaster/GetActionList`,
    getById: `${API_BASE_URL}/ActionMaster/GetActionById`,
    remove: `${API_BASE_URL}/ActionMaster/DeleteAction`,
  },
  dashboard: {
    adminSummary: `${API_BASE_URL}/TPAClaim/GetAdminDashboardDetails`,
    clientSummary: `${API_BASE_URL}/TPAClaim/GetPolicyDashboardSummary`,
    claimSummary: `${API_BASE_URL}/TPAClaim/GetAdminCliamDetails`,
    corporateSummary: `${API_BASE_URL}/CorporateMaster/CorporateSummary`,
    ticketSummary: `${API_BASE_URL}/Ticket/GetAllTicketNumber`,
    crmSummary: `${API_BASE_URL}/Employer/GetHRDashboardDefaultData`,
  },
  benefitsManagement: {
    corporates: `${API_BASE_URL}/Employer/GetDropdownCorporate`,
    policies: `${API_BASE_URL}/Employer/GetDropdownCorporatePolicy`,
    ecards: `${API_BASE_URL}/TPAEcard/GetEcardManagementData`,
    ecardBulkDownload: `${API_BASE_URL}/TPAEcard/DownloadAllEcards`,
    claims: `${API_BASE_URL}/Report/ClaimReportTableData`,
    claimsExport: `${API_BASE_URL}/Report/ClaimExcelDownload`,
    demographics: `${API_BASE_URL}/Report/DemographicReportTableData`,
    demographicsExport: `${API_BASE_URL}/Report/DemographicExcelDownload`,
  },
  tpaIntegration: {
    overview: `${API_BASE_URL}/TpaIntegrationStudio/Overview`,
    providers: `${API_BASE_URL}/TpaIntegrationStudio/Providers`,
    saveProvider: `${API_BASE_URL}/TpaIntegrationStudio/SaveProvider`,
    environments: `${API_BASE_URL}/TpaIntegrationStudio/Environments`,
    saveEnvironment: `${API_BASE_URL}/TpaIntegrationStudio/SaveEnvironment`,
    operations: `${API_BASE_URL}/TpaIntegrationStudio/Operations`,
    saveOperation: `${API_BASE_URL}/TpaIntegrationStudio/SaveOperation`,
    mappings: `${API_BASE_URL}/TpaIntegrationStudio/Mappings`,
    saveMapping: `${API_BASE_URL}/TpaIntegrationStudio/SaveMapping`,
    assignments: `${API_BASE_URL}/TpaIntegrationStudio/Assignments`,
    saveAssignment: `${API_BASE_URL}/TpaIntegrationStudio/SaveAssignment`,
    testCareUat: `${API_BASE_URL}/TpaIntegrationStudio/TestCareUat`,
    checkProviderHealth: `${API_BASE_URL}/TpaIntegrationStudio/CheckProviderHealth`,
    corporates: `${API_BASE_URL}/Employer/GetDropdownCorporate`,
    policies: `${API_BASE_URL}/Employer/GetDropdownCorporatePolicy`,
  },
  branding: {
    active: `${API_BASE_URL}/Branding/Active`,
    list: `${API_BASE_URL}/Branding/List`,
    save: `${API_BASE_URL}/Branding/Save`,
    activate: `${API_BASE_URL}/Branding/Activate`,
    disable: `${API_BASE_URL}/Branding/Disable`,
  },
  tickets: {
    queue: `${API_BASE_URL}/TicketWorkflow/Queue`,
    detail: `${API_BASE_URL}/TicketWorkflow/Detail`,
    update: `${API_BASE_URL}/TicketWorkflow/Update`,
    users: `${API_BASE_URL}/TicketWorkflow/AssignableUsers`,
    reminders: `${API_BASE_URL}/TicketWorkflow/ProcessDueReminders`,
  },

  // Corporate Master (Clients â†’ Step 1 "Profile") â€” paths match the old
  // portal's CorporateMaster / GenericMaster / *Master controllers exactly,
  // so this hits the same backend records the old Masters > Corporate
  // Master screens did.
  GetDropdownGenericCorporateMaster: `${API_BASE_URL}/GenericMaster/GetDropdownGenericCorporateMaster`,
  GetDropdownEntityMaster: `${API_BASE_URL}/EntityMaster/GetDropdownEntityMaster`,
  GetDropdownIndustryMaster: `${API_BASE_URL}/IndustryMaster/GetDropdownIndustryMaster`,
  GetDropdownGenericBrandMaster: `${API_BASE_URL}/GenericMaster/GetDropdownGenericBrandMaster`,
  GetDropdownStateMaster: `${API_BASE_URL}/StateMaster/GetDropdownStateMaster`,
  GetCityMasterByStateID: `${API_BASE_URL}/CityMaster/GetCityMasterByStateID`,
  GetDropdownfontMaster: `${API_BASE_URL}/FontMaster/GetDropdownfontMaster`,
  GetDropdownUserIdPass: `${API_BASE_URL}/GenericMaster/GetDropdownUserIdPass`,
  InsertCorporateMaster: `${API_BASE_URL}/CorporateMaster/InsertCorporateMaster`,
  UpdateCorporateMaster: `${API_BASE_URL}/CorporateMaster/UpdateCorporateMaster`,
  GetCorporateMasterById: `${API_BASE_URL}/CorporateMaster/GetCorporateMasterById`,
  GetCorporateMasterList: `${API_BASE_URL}/CorporateMaster/GetCorporateMasterList`,
  DeleteCorporateMaster: `${API_BASE_URL}/CorporateMaster/DeleteCorporateMaster`,
  Get_CorporateMaster_Export: `${API_BASE_URL}/CorporateMaster/Get_CorporateMaster_Export`,
  CorporateSummary: `${API_BASE_URL}/CorporateMaster/CorporateSummary`,
  GetCorporateStaging: `${API_BASE_URL}/CorporateMaster/GetCorporateStaging`,
  UpsertCorporate: `${API_BASE_URL}/CorporateMaster/UpsertSubCorporate`,
  UpsertSubCorporate: `${API_BASE_URL}/CorporateMaster/UpsertSubCorporate`,
  GetCorporateEntitiesList: `${API_BASE_URL}/CorporateMaster/GetCorporateEntitiesList`,
  UpsertBranchMaster: `${API_BASE_URL}/BranchMaster/UpsertBranchMaster`,
  GetBranchList: `${API_BASE_URL}/BranchMaster/GetBranchList`,
  UpsertCrmOwnerShip: `${API_BASE_URL}/CrmOwnerShip/UpsertCrmOwnerShip`,
  GetAllCrmOwnerShip: `${API_BASE_URL}/CrmOwnerShip/GetAllCrmOwnerShip`,
  GetCrmOwnerShipUserDropDown: `${API_BASE_URL}/CrmOwnerShip/GetUserDropDown`,
  GetGenericMasterByMastertypeName: `${API_BASE_URL}/GenericMaster/GetGenericMasterByMastertypeName`,

  // Employee Master / bulk employee upload (Clients -> Step 4)
  GetCorporateName: `${API_BASE_URL}/Employee/DropdownCorporate`,
  GetDesignationName: `${API_BASE_URL}/Employee/GetDropdownDesignation`,
  GetEntityName: `${API_BASE_URL}/Employee/DropdownCorporateEntity`,
  GetCorporateGrade: `${API_BASE_URL}/Employee/CorporateGrade`,
  InsertEmployeeMaster: `${API_BASE_URL}/Employee/InsertEmployeeData`,
  GetEmployeeMasterList: `${API_BASE_URL}/Employee/EmployeeDataTable`,
  GetEmployeeMasterById: `${API_BASE_URL}/Employee/EmployeeViewData`,
  UpdateEmployeeMaster: `${API_BASE_URL}/Employee/EmployeeUpdateData`,
  DeleteEmployeeMaster: `${API_BASE_URL}/Employee/EmployeeDelete`,
  GetGenderDropdown: `${API_BASE_URL}/Employee/GetGenderDropdown`,
  GetRelationMasterDropdown: `${API_BASE_URL}/RelationMaster/GetRelationMasterDropdown`,
  GetRoleName: `${API_BASE_URL}/Employee/GetDropdownRole`,
  UploadUserData: `${API_BASE_URL}/UploadUserMaster/UploadUserData`,
  GetUploadedUser: `${API_BASE_URL}/UploadUserMaster/GetUploadedUser`,
  GetEnrollmentBatch: `${API_BASE_URL}/EmployeeEnrollment/GetEnrollmentBatch`,
  CreateEnrollmentInceptionBatch: `${API_BASE_URL}/EmployeeEnrollment/CreateEnrollmentInceptionBatch`,
  corparateDropdownCaApi: `${API_BASE_URL}/Employer/GetDropdownCorporate`,

  // Policy Configuration (legacy Nivo-FlexAdmin Step 5)
  GetCorporateDropDown: `${API_BASE_URL}/CorporateMaster/GetDropdownCorporateMaster`,
  GetPolicyNameDropDown: `${API_BASE_URL}/PolicyMaster/GetPolicyMasterDropDownList`,
  GetPolicyTypeDropDown: `${API_BASE_URL}/CoverageMaster/GetCoverageMasterDropDownList`,
  InsertPolicyCoverageMaster: `${API_BASE_URL}/CoverageMaster/PolicyCoverageInsert`,
  GetPolicyCoverageMaster: `${API_BASE_URL}/CoverageMaster/GET_COVERAGE_MASTER_LIST`,
  DeletePolicyCoverageMaster: `${API_BASE_URL}/CoverageMaster/GET_COVERAGE_MASTER_DELETE`,
  GetPolicyCoverageMasterGetByID: `${API_BASE_URL}/CoverageMaster/GET_COVERAGE_MASTER_LIST_BY_ID`,
  UpdatePolicyCoverageMaster: `${API_BASE_URL}/CoverageMaster/GET_COVERAGE_MASTER_UPDATE`,
  GetPolicyProductType: `${API_BASE_URL}/PolicyConfiguration/GetPolicyProductType`,
  GetPolicyConfigurationForEdit: `${API_BASE_URL}/PolicyConfiguration/GetPolicyConfigurationForEdit`,
  GetPolicyCoverageMasterList: `${API_BASE_URL}/PolicyConfiguration/GetPolicyCoverageMasterList`,
  GetGPAGTLPolicyCoverageMasterList: `${API_BASE_URL}/PolicyConfiguration/GetGPAGTLPolicyCoverageMasterList`,
  GetGPAGTLPolicyDropDownListEdit: `${API_BASE_URL}/PolicyMaster/GetGPAGTLPolicyDropDownListEdit`,
  GetGenericMasterList: `${API_BASE_URL}/Common/GetGenericMasterdropdownList`,
  GetDefaultRelationForConfiguration: `${API_BASE_URL}/PolicyConfiguration/GetDefaultRelationForConfiguration`,
  RelationForConfiguration: `${API_BASE_URL}/Common/GetGenericMasterDropDownList`,
  GetExtraSettingMasterDefaultList: `${API_BASE_URL}/PolicyConfiguration/GetExtraSettingMasterDefaultList`,
  InsertPolicyCoverage: `${API_BASE_URL}/PolicyConfiguration/InsertPolicyCoverage`,
  UpdatePolicyCoverage: `${API_BASE_URL}/PolicyConfiguration/UpdatePolicyCoverage`,
  InsertPolicyDependentDetails: `${API_BASE_URL}/PolicyConfiguration/InsertPolicyDependentDetails`,
  UpdatePolicyDependentDetails: `${API_BASE_URL}/PolicyConfiguration/UpdatePolicyDependentDetails`,
  InsertPolicyRelationGroupDetails: `${API_BASE_URL}/PolicyConfiguration/InsertPolicyRelationGroupDetails`,
  UpdatePolicyRelationGroupDetails: `${API_BASE_URL}/PolicyConfiguration/UpdatePolicyRelationGroupDetails`,
  InsertPolicySumInsuredDetails: `${API_BASE_URL}/PolicyConfiguration/InsertPolicySumInsuredDetails`,
  UpdatePolicySumInsuredDetails: `${API_BASE_URL}/PolicyConfiguration/UpdatePolicySumInsuredDetails`,
  InsertPolicyPremiumDetails: `${API_BASE_URL}/PolicyConfiguration/InsertPolicyPremiumDetails`,
  UpdatePolicyPremiumDetails: `${API_BASE_URL}/PolicyConfiguration/UpdatePolicyPremiumDetails`,
  InsertExtraSettingDetails: `${API_BASE_URL}/PolicyConfiguration/InsertExtraSettingDetails`,
  UpdateExtraSettingDetails: `${API_BASE_URL}/PolicyConfiguration/UpdateExtraSettingDetails`,

  // Policy Benefits (legacy Nivo-FlexAdmin PolicyBenefit master)
  GetProductPolicyBenefitCoverage: `${API_BASE_URL}/BenefitMaster/GetProductforBenefitMAster`,
  GetProductPolicyBenefitTable: `${API_BASE_URL}/BenefitMaster/GetPolicyPlanforBenefitMAster`,
  GetPolicywithoutcorporate: `${API_BASE_URL}/BenefitMaster/GetPolicyMasterforBenefitMAster`,
  InsertPolicyBenefits: `${API_BASE_URL}/BenefitMaster/POLICY_BENIFIT_INSET_LOOP`,
  PolicyBenefitDataTable: `${API_BASE_URL}/BenefitMaster/BENEFIT_MASTER_DATATABLE`,
  PolicyBenefitMasterDelete: `${API_BASE_URL}/BenefitMaster/DELETE_BENEFIT_MASTER`,
  PolicyBenefitMasterView: `${API_BASE_URL}/BenefitMaster/VIEW_BENEFIT_MASTER`,
  PolicyBenefitMasterDownloadFile: `${API_BASE_URL}/BenefitMaster/DownloadFile`,
  PolicyBenefitMasterEdit: `${API_BASE_URL}/BenefitMaster/EDIT_BENEFIT_MASTER`,
  PolicyBenefitMasterUpdate: `${API_BASE_URL}/BenefitMaster/PolicyEnrollmentUpdate`,
  PolicyBenefitMasteGetAll: `${API_BASE_URL}/BenefitMaster/GetAllBenefitMAster`,
  Get_Benefit_Export: `${API_BASE_URL}/BenefitMaster/Get_Benefit_Export`,

  // Special Policy Benefits / Branding
  GetAllPolicySpecialBenefits: `${API_BASE_URL}/PolicySpecialBenefitService/GetAllPolicySpecialBenefits`,
  GetPolicySpecialBenefitsById: `${API_BASE_URL}/PolicySpecialBenefitService/GetPolicySpecialBenefitsById`,
  UpsertPolicySpecialBenefits: `${API_BASE_URL}/PolicySpecialBenefitService/UpsertPolicySpecialBenefits`,

  // Policy Document / Document Master (legacy Nivo-FlexAdmin Document master)
  GetDropdownDocument_Type: `${API_BASE_URL}/GenericMaster/GetDropdownDocument_Type`,
  InsertdocumentMaster: `${API_BASE_URL}/documentMaster/InsertdocumentMaster`,
  GetdocumentMasterList: `${API_BASE_URL}/documentMaster/GetdocumentMasterList`,
  GetdocumentMasterById: `${API_BASE_URL}/documentMaster/GetdocumentMasterById`,
  UpdatedocumentMaster: `${API_BASE_URL}/documentMaster/UpdatedocumentMaster`,
  DeletedocumentMaster: `${API_BASE_URL}/documentMaster/DeletedocumentMaster`,
  Get_Document_Master_Export: `${API_BASE_URL}/documentMaster/Get_Document_Master_Export`,

  // Escalation / Contact Master (legacy Nivo-FlexAdmin Contact master)
  Get_ContactMaster_Export: `${API_BASE_URL}/ContactMaster/Get_ContactMaster_Export`,
  GetContactMasterList: `${API_BASE_URL}/ContactMaster/GetContactMasterList`,
  GetContactMasterViewList: `${API_BASE_URL}/ContactMaster/GetContactMasterViewList`,
  GetContactMasterById: `${API_BASE_URL}/ContactMaster/GetContactMasterById`,
  GetDropdownContactFor: `${API_BASE_URL}/GenericMaster/GetDropdownContactFor`,
  GetDropdownContactLevel: `${API_BASE_URL}/GenericMaster/GetDropdownContactLevel`,
  InsertContactMaster: `${API_BASE_URL}/ContactMaster/InsertContactMaster`,
  DeleteContactMaster: `${API_BASE_URL}/ContactMaster/DeleteContactMaster`,
  UpdateContactMaster: `${API_BASE_URL}/ContactMaster/UpdateContactMaster`,
  DelContactMasterByCorporateID: `${API_BASE_URL}/ContactMaster/DelContactMasterByCorporateID`,

  // Policy Assignment / Enrollment Window (legacy enrollment flow)
  GetPolicyEnrollmentDashboard: `${API_BASE_URL}/PolicyFinalize/GetPolicyEnrollmentDashboard`,
  PolicyFinalizeUpdate: `${API_BASE_URL}/PolicyFinalize/PolicyFinalizeUpdate`,
  GetPolicyFinalizeList: `${API_BASE_URL}/PolicyFinalize/GetPolicyFinalizeList`,
  PolicyFinalzeDataTable: `${API_BASE_URL}/PolicyFinalize/PolicyFinalizeDataTable`,
  GetBatchListByCorporateId: `${API_BASE_URL}/PolicyFinalize/GetBatchListByCorporateId`,
  GetUnAssignedPolicyEmployee: `${API_BASE_URL}/PolicyFinalize/GetUnAssignedPolicyEmployee`,
  GetBatchList: `${API_BASE_URL}/Endorsement/GetBatchList`,
  GetOperationListForEnrollment: `${API_BASE_URL}/PolicyEnrollment/GetOperationListForEnrollment`,
  GetEnrollmentWindowEmployeeList: `${API_BASE_URL}/PolicyEnrollment/GetEnrollmentWindowEmployeeList`,
  PolicyEnrollmentInvitationMail: `${API_BASE_URL}/PolicyEnrollment/EmailContentByCorporateIDForInvitation`,
  PolicyEnrollmentConfirmationMail: `${API_BASE_URL}/PolicyEnrollment/EmailContentByCorporateIDForConfirmation`,
  GetEnrollmentDashboard: `${API_BASE_URL}/PolicyEnrollment/GetEnrollmentDashboard`,
  PolicyEnrollmentInsert: `${API_BASE_URL}/PolicyEnrollment/PolicyEnrollmentInsert`,
  GetPolicyEnrollmentList: `${API_BASE_URL}/PolicyEnrollment/GetPolicyEnrollmentList`,
  PolicyEnrollmentDataTable: `${API_BASE_URL}/PolicyEnrollment/PolicyEnrollmentDataTable`,
  PolicyEnrollmentViewDataTable: `${API_BASE_URL}/PolicyEnrollment/PolicyEnrollmentViewDataTable`,
};



export const apiurls = apiUrls;

export default apiUrls;
